### ISSUE TITLE
File Missing: filerenderer.swift

### ISSUE THREAD

**Issue by Mysticsocialstar** [Lzcstan/iOS3DFaceRecon#2]
Please check about the file "filerenderer.swift". When I open your code in xcode it says this file is missing. Thanks in advance!

**Comment by Lzcstan** [comment]
Sorry for the late reply. But I think your issue may also have typos. Regarding your question, I initially searched all the files in the repository and could not find the word "filerenderer". It was only recently that I had time to try to understand your original intention and found a solution.

In fact, if you further read the [README.md](https://github.com/Lzcstan/iOS3DFaceRecon/blob/main/README.md) of this repository, I believe you can find the answer yourself. This project is part of my undergraduate graduation project, which relies on Apple's sample code. But I am not a senior engineer in iOS application development, so when uploading the code, I chose to replace the .xcodeproj file that originally contained my Apple developer ID information with the .xcodeproj file in Apple's sample code. This resulted in code files that were originally in the sample code but not used by me also appearing in the .xcodeproj file of the project. I apologize for the trouble this choice has caused you.

The main reason why the original code files in the sample code are abandoned is that the application compiled by the sample code has two viewers for taking depth pictures and visualizing, and the purpose of this repository is to obtain the RGB-D file of the face by taking pictures. In order to reduce compilation time, I deleted all code for visual viewer.

Download Apple's sample code and compare it with this repository, you can see that I deleted a total of two code files, one of which is named "**FilterRenderer.swift**", which should be the file you want. I've added these two files in the latest [**commit**](https://github.com/Lzcstan/iOS3DFaceRecon/commit/af716a9426611814f9ab2ba16cb99f2a4282e1ff).

Please note that without these two files, the functions of the original repository are complete. You only need to create a new Xcode project and generate a new .xcodeproj file.

I hope my reply can answer your issue. If you have any questions, please feel free to send me an email.
